name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - version-*
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - name: Build project PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
      - run: composer install --prefer-dist --no-dev -o --ignore-platform-reqs
      - run: |
          echo "Remove useless folders"
          cp .distignore .gitignore

          tag=$(echo '${{ github.ref }}' | grep -Po '(?<=version-)[^;]+')
          git status
          git add .
          git status
          echo tag