name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - version-*
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - name: Build project PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
      - run: composer install --prefer-dist --no-dev -o --ignore-platform-reqs
      - run: |
          echo "Get Branch tag"
          TAG=$(echo '${{ github.ref }}' | grep -Po '(?<=version-)[^;]+')

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag exists, stop now";
            exit 0;
          fi

          echo "Copy .distignore to .gitignore"
          cp .distignore .gitignore

          echo "Configure git"
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"

          echo "Creating tag ${TAG}"
          git add .
          git add -u
          git commit -m "Create tag ${TAG}"
          git tag ${TAG}
          git push --tags
          git push